/*
 *  Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com)
 *
 *  WSO2 LLC. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

package io.ballerina.modelgenerator.commons;

import java.util.List;

/**
 * Deserialization target for a connector's own <b>{@code resources/trigger-authoring.json}</b> — the
 * authoring-rules overlay that sits above the syntax tree and semantic model: presence rules,
 * {@code oneOf} cross-construct relationships, identifier/base-path semantics, and handler shapes for
 * service types with no concrete backing type.
 *
 * <p>Deliberately separate from {@link TriggerMetadata} (the existing, display-only
 * {@code resources/trigger-metadata.json} sibling used for tree-node name/icon/label) and from the
 * much larger, fully UI-ready {@code trigger-model.json} (a {@code TriggerModel} Property/codedata
 * tree, hand-authored or generated by the {@code generate-trigger-model} tooling). This document
 * carries only what a coding agent or the language server <b>cannot</b> recover by introspecting the
 * library itself (per the governing DRY principle: everything the compiler API can already tell you —
 * a listener's init signature, a concrete service type's declared methods, an annotation record's
 * field shapes — is referenced by name here, never restated). A {@link TriggerModel}-equivalent is
 * synthesized at request time by combining this document with semantic-API introspection of the
 * referenced types.
 *
 * <p>Omit {@link #annotations} / {@link #dataBindingRules} entirely when the connector has none — an
 * empty array is never used in their place, consistent with the rest of this schema: a field that
 * would be empty, unused, or fully derivable from other fields is left out.
 *
 * @param listeners        the connector's listener entry point(s); always at least one — a listener
 *                         is structurally required, so there is no presence marker on this array
 * @param serviceTypes     the connector's service-type alternatives. Exactly one entry means it is the
 *                         (only, required) service type; more than one entry means each is
 *                         individually optional and the choice of which to implement is left to
 *                         whatever supplied the generation intent
 * @param annotations      registry of annotation types referenced elsewhere in this document, defined
 *                         once; {@code null}/absent when the connector declares none
 * @param dataBindingRules registry of payload/data-binding modes referenced from
 *                         {@code serviceTypes[].handlers.options[].params[].dataBinding}, defined
 *                         once; {@code null}/absent when the connector declares none
 * @since 1.10.0
 */
public record TriggerAuthoringModel(
        List<Listener> listeners,
        List<AuthoringServiceType> serviceTypes,
        List<AuthoringAnnotation> annotations,
        List<AuthoringDataBindingRule> dataBindingRules) {

    /**
     * A listener entry point. No init fields are ever modeled here — a listener's init signature is
     * introspectable (the governing DRY principle), so a generator gets real init parameters from the
     * library itself, not from this file. There is no {@code presence} field — a listener is always
     * structurally required.
     *
     * @param type            the listener class
     * @param services        the {@link AuthoringServiceType#id()} values this listener can host
     * @param requiredImports packages that must be imported for side effect even though nothing in the
     *                        generated code references them by name (e.g. a generic engine needing a
     *                        specific driver registered at runtime); {@code null}/absent when the
     *                        connector needs no such import
     */
    public record Listener(TypeRef type, List<String> services, List<RequiredImport> requiredImports) {
    }

    /**
     * A package that must be imported for its side effect (e.g. {@code import ballerinax/mssql.cdc.driver as _;})
     * even though nothing in the generated code references it by name.
     *
     * @param importType  the reason the import is required; {@link #IMPORT_TYPE_DRIVER} is the only
     *                    value seen in the corpus this schema was built against
     * @param packageInfo the coordinates of the package to import
     */
    public record RequiredImport(String importType, TypeRef.PackageInfo packageInfo) {

        public static final String IMPORT_TYPE_DRIVER = "driver";
    }
}
